version: "3.8"
networks:
  app-tier:
    driver: bridge
services:
  db:
    build: ./db
    environment:
      - MYSQL_ROOT_PASSWORD=Aswift07
      - MYSQL_DATABASE=FRENCHDB
    ports: 
      - "3306:3306"
    restart: always
    networks:
      - app-tier
  web:
    build: ./web
    environment:
      - MYSQL_DATABASE=FRENCHDB
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Aswift07
      - MYSQL_HOST=db
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
      - SID=${SID}
      - AUTH_TOKEN=${AUTH_TOKEN}
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: on-failure

    # Trying to resolve the node modules issue
    # volumes:
    #   - /usr/src/app
    #   - /usr/src/app/node_modules
    networks:
      - app-tier


# docker-compose build --no-cache && docker-compose up     