version: "3.8"
networks:
  app-tier:
    driver: bridge
services:
  db:
    build: 
      context: ./db
      args:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports: 
      - "3306:3306"
    restart: always
    networks:
      - app-tier
  web:
    build: ./web
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
      - SID=${SID}
      - AUTH_TOKEN=${AUTH_TOKEN}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: on-failure

    # Trying to resolve the node modules issue
    # volumes:
    #   - /usr/src/app
    #   - /usr/src/app/node_modules
    networks:
      - app-tier


# docker-compose build --no-cache && docker-compose up     